### ISSUE TITLE
Document repository

### ISSUE THREAD

**Issue by VictorNS69** [alastria/alastriaID-truffle-contracts#5]
Add needed documentation

**Comment by alejandroalffer** [comment]
Some changes in https://github.com/alastria/alastria-identity/wiki.

@VictorNS69, is Trello/Miro still in use?

**Comment by VictorNS69** [comment]
I don't think so. We migrated all our boards to GitHub, and Trello is kinda outdated.

Im not sure about Miro.

**Comment by alejandroalffer** [comment]
The information has been updated on the alastria-identity wiki, and the rest of the project's repositories now point to it. We leave the SU open to continue improving the onBoarding process for new developers and users

**Comment by VictorNS69** [comment]
Needed points to be documented:
- [x] NPM scripts (inside `package.json`)
- [x] Truffle versions
- [x] Configurations used
- [x] Smart Contracts structure
- [x] How to test this in a test network

Also rename the repository and all related documentation to `alastriaID-truffle-contracts`

**Comment by cmoralesdiego** [comment]
For the first point I don't know the detail that you want. As well, for the second one, just mention the 5.1.53 version which it is installed once you run the npm i ?

**Comment by VictorNS69** [comment]
For the first point, we want to explain what the command does. For example, "the command `compile` compiles the Smart contracts". I think that with this little explanation is enough.

To be honest, I'm not sure what we should explain in the second point. Any hint @nefera606 ?

**Comment by cmoralesdiego** [comment]
Everything is written in #31 .
